# Generated by Django 3.2.6 on 2021-09-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('room_name', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=150)),
                ('count', models.PositiveIntegerField(default=0)),
                ('room', models.CharField(max_length=5)),
                ('channel_name', models.CharField(max_length=255)),
                ('is_in_the_room', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('first_field', models.CharField(max_length=150, null=True)),
                ('second_field', models.CharField(max_length=150, null=True)),
                ('first_count', models.IntegerField()),
                ('second_count', models.IntegerField()),
                ('group_channel_name', models.CharField(max_length=255, null=True)),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_field_for_the_first', to='chat.player')),
                ('messages', models.ManyToManyField(blank=True, to='chat.Message')),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_field_for_the_second', to='chat.player')),
                ('whos_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='chat.player')),
            ],
        ),
    ]
