# Generated by Django 3.2.6 on 2021-09-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210917_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
    ]
