# Generated by Django 3.2.6 on 2021-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210917_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='channel_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
